name: food_ai_thesis
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  image_picker: ^0.8.9
  google_generative_ai: ^0.4.5
  http: ^1.2.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_zoom_drawer: ^3.2.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  path_provider: ^2.0.11
  provider: ^6.1.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  tflite_flutter: ^0.11.0
  image: ^4.0.15
  logger: ^2.5.0
  flutter_spinkit: ^5.2.0
  qr_flutter: ^4.1.0 
  pdf: ^3.11.3
  printing: ^5.12.0
  permission_handler: ^11.4.0



dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
   android: true
   ios: true
   image_path: "assets/foodlogo.png"



flutter:
  uses-material-design: true
  assets:
   - lib/assets/
  #  - lib/assets/food_classification_model_v3.tflite
   - lib/assets/labels.txt

